# Form implementation generated from reading ui file 'peres_with_povt.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_peresWithPovt(object):
    def setupUi(self, peresWithPovt):
        peresWithPovt.setObjectName("peresWithPovt")
        peresWithPovt.resize(380, 195)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(peresWithPovt.sizePolicy().hasHeightForWidth())
        peresWithPovt.setSizePolicy(sizePolicy)
        peresWithPovt.setMinimumSize(QtCore.QSize(380, 195))
        peresWithPovt.setMaximumSize(QtCore.QSize(380, 195))
        self.centralwidget = QtWidgets.QWidget(peresWithPovt)
        self.centralwidget.setMinimumSize(QtCore.QSize(380, 183))
        self.centralwidget.setMaximumSize(QtCore.QSize(380, 183))
        self.centralwidget.setObjectName("centralwidget")
        self.equal = QtWidgets.QLabel(self.centralwidget)
        self.equal.setGeometry(QtCore.QRect(130, 30, 31, 81))
        font = QtGui.QFont()
        font.setFamily("Play")
        font.setPointSize(36)
        self.equal.setFont(font)
        self.equal.setObjectName("equal")
        self.letter = QtWidgets.QLabel(self.centralwidget)
        self.letter.setGeometry(QtCore.QRect(20, 20, 61, 91))
        font = QtGui.QFont()
        font.setFamily("Play")
        font.setPointSize(48)
        self.letter.setFont(font)
        self.letter.setObjectName("letter")
        self.submit = QtWidgets.QPushButton(self.centralwidget)
        self.submit.setGeometry(QtCore.QRect(20, 130, 111, 28))
        font = QtGui.QFont()
        font.setFamily("Play")
        font.setPointSize(10)
        self.submit.setFont(font)
        self.submit.setObjectName("submit")
        self.result = QtWidgets.QLabel(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(170, 40, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Play")
        font.setPointSize(20)
        self.result.setFont(font)
        self.result.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.result.setWordWrap(False)
        self.result.setObjectName("result")
        self.inputline = QtWidgets.QLineEdit(self.centralwidget)
        self.inputline.setGeometry(QtCore.QRect(20, 100, 141, 22))
        font = QtGui.QFont()
        font.setFamily("Play")
        font.setPointSize(11)
        self.inputline.setFont(font)
        self.inputline.setText("")
        self.inputline.setObjectName("inputline")
        peresWithPovt.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(peresWithPovt)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 380, 26))
        self.menubar.setObjectName("menubar")
        peresWithPovt.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(peresWithPovt)
        self.statusbar.setObjectName("statusbar")
        peresWithPovt.setStatusBar(self.statusbar)

        self.retranslateUi(peresWithPovt)
        QtCore.QMetaObject.connectSlotsByName(peresWithPovt)

    def retranslateUi(self, peresWithPovt):
        _translate = QtCore.QCoreApplication.translate
        peresWithPovt.setWindowTitle(_translate("peresWithPovt", "Перестановка с повторениями"))
        self.equal.setText(_translate("peresWithPovt", "="))
        self.letter.setText(_translate("peresWithPovt", "P"))
        self.submit.setText(_translate("peresWithPovt", "Вычислить"))
        self.result.setText(_translate("peresWithPovt", "<html><head/><body><p><br/></p></body></html>"))
        self.inputline.setPlaceholderText(_translate("peresWithPovt", "m1,m2,..,mk"))
